/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditTrail service. Represents a row in the &quot;audit_trail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.AuditTrailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.AuditTrailImpl}.
 * </p>
 *
 * @author Dave Man
 * @see AuditTrail
 * @see hk.org.hkbh.cms.outpatient.model.impl.AuditTrailImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.AuditTrailModelImpl
 * @generated
 */
@ProviderType
public interface AuditTrailModel extends BaseModel<AuditTrail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit trail model instance should use the {@link AuditTrail} interface instead.
	 */

	/**
	 * Returns the primary key of this audit trail.
	 *
	 * @return the primary key of this audit trail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit trail.
	 *
	 * @param primaryKey the primary key of this audit trail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this audit trail.
	 *
	 * @return the ID of this audit trail
	 */
	public long getId();

	/**
	 * Sets the ID of this audit trail.
	 *
	 * @param id the ID of this audit trail
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this audit trail.
	 *
	 * @return the user ID of this audit trail
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this audit trail.
	 *
	 * @param userId the user ID of this audit trail
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the function ID of this audit trail.
	 *
	 * @return the function ID of this audit trail
	 */
	public Long getFunctionId();

	/**
	 * Sets the function ID of this audit trail.
	 *
	 * @param functionId the function ID of this audit trail
	 */
	public void setFunctionId(Long functionId);

	/**
	 * Returns the patient ID of this audit trail.
	 *
	 * @return the patient ID of this audit trail
	 */
	public Long getPatientId();

	/**
	 * Sets the patient ID of this audit trail.
	 *
	 * @param patientId the patient ID of this audit trail
	 */
	public void setPatientId(Long patientId);

	/**
	 * Returns the episode ID of this audit trail.
	 *
	 * @return the episode ID of this audit trail
	 */
	public Long getEpisodeId();

	/**
	 * Sets the episode ID of this audit trail.
	 *
	 * @param episodeId the episode ID of this audit trail
	 */
	public void setEpisodeId(Long episodeId);

	/**
	 * Returns the class name of this audit trail.
	 *
	 * @return the class name of this audit trail
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this audit trail.
	 *
	 * @param className the class name of this audit trail
	 */
	public void setClassName(String className);

	/**
	 * Returns the user action of this audit trail.
	 *
	 * @return the user action of this audit trail
	 */
	@AutoEscape
	public String getUserAction();

	/**
	 * Sets the user action of this audit trail.
	 *
	 * @param userAction the user action of this audit trail
	 */
	public void setUserAction(String userAction);

	/**
	 * Returns the before image in json of this audit trail.
	 *
	 * @return the before image in json of this audit trail
	 */
	@AutoEscape
	public String getBeforeImageInJson();

	/**
	 * Sets the before image in json of this audit trail.
	 *
	 * @param beforeImageInJson the before image in json of this audit trail
	 */
	public void setBeforeImageInJson(String beforeImageInJson);

	/**
	 * Returns the after image in json of this audit trail.
	 *
	 * @return the after image in json of this audit trail
	 */
	@AutoEscape
	public String getAfterImageInJson();

	/**
	 * Sets the after image in json of this audit trail.
	 *
	 * @param afterImageInJson the after image in json of this audit trail
	 */
	public void setAfterImageInJson(String afterImageInJson);

	/**
	 * Returns the is deleted of this audit trail.
	 *
	 * @return the is deleted of this audit trail
	 */
	@AutoEscape
	public String getIsDeleted();

	/**
	 * Sets the is deleted of this audit trail.
	 *
	 * @param isDeleted the is deleted of this audit trail
	 */
	public void setIsDeleted(String isDeleted);

	/**
	 * Returns the create date of this audit trail.
	 *
	 * @return the create date of this audit trail
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this audit trail.
	 *
	 * @param createDate the create date of this audit trail
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this audit trail.
	 *
	 * @return the update date of this audit trail
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this audit trail.
	 *
	 * @param updateDate the update date of this audit trail
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this audit trail.
	 *
	 * @return the created by of this audit trail
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this audit trail.
	 *
	 * @param createdBy the created by of this audit trail
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this audit trail.
	 *
	 * @return the updated by of this audit trail
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this audit trail.
	 *
	 * @param updatedBy the updated by of this audit trail
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AuditTrail auditTrail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AuditTrail> toCacheModel();

	@Override
	public AuditTrail toEscapedModel();

	@Override
	public AuditTrail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}