/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ClinicalNoteTemplate service. Represents a row in the &quot;clinical_note_template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.ClinicalNoteTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.ClinicalNoteTemplateImpl}.
 * </p>
 *
 * @author Dave Man
 * @see ClinicalNoteTemplate
 * @see hk.org.hkbh.cms.outpatient.model.impl.ClinicalNoteTemplateImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.ClinicalNoteTemplateModelImpl
 * @generated
 */
@ProviderType
public interface ClinicalNoteTemplateModel extends BaseModel<ClinicalNoteTemplate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clinical note template model instance should use the {@link ClinicalNoteTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this clinical note template.
	 *
	 * @return the primary key of this clinical note template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clinical note template.
	 *
	 * @param primaryKey the primary key of this clinical note template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this clinical note template.
	 *
	 * @return the ID of this clinical note template
	 */
	public long getId();

	/**
	 * Sets the ID of this clinical note template.
	 *
	 * @param id the ID of this clinical note template
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this clinical note template.
	 *
	 * @return the user ID of this clinical note template
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this clinical note template.
	 *
	 * @param userId the user ID of this clinical note template
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the template type code ID of this clinical note template.
	 *
	 * @return the template type code ID of this clinical note template
	 */
	public Long getTemplateTypeCodeId();

	/**
	 * Sets the template type code ID of this clinical note template.
	 *
	 * @param templateTypeCodeId the template type code ID of this clinical note template
	 */
	public void setTemplateTypeCodeId(Long templateTypeCodeId);

	/**
	 * Returns the template name of this clinical note template.
	 *
	 * @return the template name of this clinical note template
	 */
	@AutoEscape
	public String getTemplateName();

	/**
	 * Sets the template name of this clinical note template.
	 *
	 * @param templateName the template name of this clinical note template
	 */
	public void setTemplateName(String templateName);

	/**
	 * Returns the template content of this clinical note template.
	 *
	 * @return the template content of this clinical note template
	 */
	@AutoEscape
	public String getTemplateContent();

	/**
	 * Sets the template content of this clinical note template.
	 *
	 * @param templateContent the template content of this clinical note template
	 */
	public void setTemplateContent(String templateContent);

	/**
	 * Returns the template content html of this clinical note template.
	 *
	 * @return the template content html of this clinical note template
	 */
	@AutoEscape
	public String getTemplateContentHtml();

	/**
	 * Sets the template content html of this clinical note template.
	 *
	 * @param templateContentHtml the template content html of this clinical note template
	 */
	public void setTemplateContentHtml(String templateContentHtml);

	/**
	 * Returns the create date of this clinical note template.
	 *
	 * @return the create date of this clinical note template
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this clinical note template.
	 *
	 * @param createDate the create date of this clinical note template
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this clinical note template.
	 *
	 * @return the update date of this clinical note template
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this clinical note template.
	 *
	 * @param updateDate the update date of this clinical note template
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this clinical note template.
	 *
	 * @return the created by of this clinical note template
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this clinical note template.
	 *
	 * @param createdBy the created by of this clinical note template
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this clinical note template.
	 *
	 * @return the updated by of this clinical note template
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this clinical note template.
	 *
	 * @param updatedBy the updated by of this clinical note template
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ClinicalNoteTemplate clinicalNoteTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ClinicalNoteTemplate> toCacheModel();

	@Override
	public ClinicalNoteTemplate toEscapedModel();

	@Override
	public ClinicalNoteTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}