/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Code service. Represents a row in the &quot;code&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.CodeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.CodeImpl}.
 * </p>
 *
 * @author Dave Man
 * @see Code
 * @see hk.org.hkbh.cms.outpatient.model.impl.CodeImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.CodeModelImpl
 * @generated
 */
@ProviderType
public interface CodeModel extends BaseModel<Code> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a code model instance should use the {@link Code} interface instead.
	 */

	/**
	 * Returns the primary key of this code.
	 *
	 * @return the primary key of this code
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this code.
	 *
	 * @param primaryKey the primary key of this code
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this code.
	 *
	 * @return the ID of this code
	 */
	public int getId();

	/**
	 * Sets the ID of this code.
	 *
	 * @param id the ID of this code
	 */
	public void setId(int id);

	/**
	 * Returns the master code of this code.
	 *
	 * @return the master code of this code
	 */
	@AutoEscape
	public String getMasterCode();

	/**
	 * Sets the master code of this code.
	 *
	 * @param masterCode the master code of this code
	 */
	public void setMasterCode(String masterCode);

	/**
	 * Returns the display text en of this code.
	 *
	 * @return the display text en of this code
	 */
	@AutoEscape
	public String getDisplayTextEn();

	/**
	 * Sets the display text en of this code.
	 *
	 * @param displayTextEn the display text en of this code
	 */
	public void setDisplayTextEn(String displayTextEn);

	/**
	 * Returns the display text chi of this code.
	 *
	 * @return the display text chi of this code
	 */
	@AutoEscape
	public String getDisplayTextChi();

	/**
	 * Sets the display text chi of this code.
	 *
	 * @param displayTextChi the display text chi of this code
	 */
	public void setDisplayTextChi(String displayTextChi);

	/**
	 * Returns the active of this code.
	 *
	 * @return the active of this code
	 */
	public Boolean getActive();

	/**
	 * Sets the active of this code.
	 *
	 * @param active the active of this code
	 */
	public void setActive(Boolean active);

	/**
	 * Returns the subcode enabled of this code.
	 *
	 * @return the subcode enabled of this code
	 */
	public Boolean getSubcodeEnabled();

	/**
	 * Sets the subcode enabled of this code.
	 *
	 * @param subcodeEnabled the subcode enabled of this code
	 */
	public void setSubcodeEnabled(Boolean subcodeEnabled);

	/**
	 * Returns the remarks of this code.
	 *
	 * @return the remarks of this code
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this code.
	 *
	 * @param remarks the remarks of this code
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the create date of this code.
	 *
	 * @return the create date of this code
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this code.
	 *
	 * @param createDate the create date of this code
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this code.
	 *
	 * @return the update date of this code
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this code.
	 *
	 * @param updateDate the update date of this code
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this code.
	 *
	 * @return the created by of this code
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this code.
	 *
	 * @param createdBy the created by of this code
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this code.
	 *
	 * @return the updated by of this code
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this code.
	 *
	 * @param updatedBy the updated by of this code
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Code code);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Code> toCacheModel();

	@Override
	public Code toEscapedModel();

	@Override
	public Code toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}