/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CodeDetail service. Represents a row in the &quot;code_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.CodeDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.CodeDetailImpl}.
 * </p>
 *
 * @author Dave Man
 * @see CodeDetail
 * @see hk.org.hkbh.cms.outpatient.model.impl.CodeDetailImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.CodeDetailModelImpl
 * @generated
 */
@ProviderType
public interface CodeDetailModel extends BaseModel<CodeDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a code detail model instance should use the {@link CodeDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this code detail.
	 *
	 * @return the primary key of this code detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this code detail.
	 *
	 * @param primaryKey the primary key of this code detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this code detail.
	 *
	 * @return the ID of this code detail
	 */
	public long getId();

	/**
	 * Sets the ID of this code detail.
	 *
	 * @param id the ID of this code detail
	 */
	public void setId(long id);

	/**
	 * Returns the code ID of this code detail.
	 *
	 * @return the code ID of this code detail
	 */
	@AutoEscape
	public String getCodeId();

	/**
	 * Sets the code ID of this code detail.
	 *
	 * @param codeId the code ID of this code detail
	 */
	public void setCodeId(String codeId);

	/**
	 * Returns the detail code of this code detail.
	 *
	 * @return the detail code of this code detail
	 */
	public Long getDetailCode();

	/**
	 * Sets the detail code of this code detail.
	 *
	 * @param detailCode the detail code of this code detail
	 */
	public void setDetailCode(Long detailCode);

	/**
	 * Returns the seq of this code detail.
	 *
	 * @return the seq of this code detail
	 */
	public Integer getSeq();

	/**
	 * Sets the seq of this code detail.
	 *
	 * @param seq the seq of this code detail
	 */
	public void setSeq(Integer seq);

	/**
	 * Returns the display text en of this code detail.
	 *
	 * @return the display text en of this code detail
	 */
	@AutoEscape
	public String getDisplayTextEn();

	/**
	 * Sets the display text en of this code detail.
	 *
	 * @param displayTextEn the display text en of this code detail
	 */
	public void setDisplayTextEn(String displayTextEn);

	/**
	 * Returns the display text chi of this code detail.
	 *
	 * @return the display text chi of this code detail
	 */
	@AutoEscape
	public String getDisplayTextChi();

	/**
	 * Sets the display text chi of this code detail.
	 *
	 * @param displayTextChi the display text chi of this code detail
	 */
	public void setDisplayTextChi(String displayTextChi);

	/**
	 * Returns the symbol of this code detail.
	 *
	 * @return the symbol of this code detail
	 */
	@AutoEscape
	public String getSymbol();

	/**
	 * Sets the symbol of this code detail.
	 *
	 * @param symbol the symbol of this code detail
	 */
	public void setSymbol(String symbol);

	/**
	 * Returns the symbol_html_code of this code detail.
	 *
	 * @return the symbol_html_code of this code detail
	 */
	@AutoEscape
	public String getSymbol_html_code();

	/**
	 * Sets the symbol_html_code of this code detail.
	 *
	 * @param symbol_html_code the symbol_html_code of this code detail
	 */
	public void setSymbol_html_code(String symbol_html_code);

	/**
	 * Returns the active of this code detail.
	 *
	 * @return the active of this code detail
	 */
	public Boolean getActive();

	/**
	 * Sets the active of this code detail.
	 *
	 * @param active the active of this code detail
	 */
	public void setActive(Boolean active);

	/**
	 * Returns the level of this code detail.
	 *
	 * @return the level of this code detail
	 */
	public Integer getLevel();

	/**
	 * Sets the level of this code detail.
	 *
	 * @param level the level of this code detail
	 */
	public void setLevel(Integer level);

	/**
	 * Returns the up level ID of this code detail.
	 *
	 * @return the up level ID of this code detail
	 */
	public Long getUpLevelId();

	/**
	 * Sets the up level ID of this code detail.
	 *
	 * @param upLevelId the up level ID of this code detail
	 */
	public void setUpLevelId(Long upLevelId);

	/**
	 * Returns the remarks of this code detail.
	 *
	 * @return the remarks of this code detail
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this code detail.
	 *
	 * @param remarks the remarks of this code detail
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the create date of this code detail.
	 *
	 * @return the create date of this code detail
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this code detail.
	 *
	 * @param createDate the create date of this code detail
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this code detail.
	 *
	 * @return the update date of this code detail
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this code detail.
	 *
	 * @param updateDate the update date of this code detail
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this code detail.
	 *
	 * @return the created by of this code detail
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this code detail.
	 *
	 * @param createdBy the created by of this code detail
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this code detail.
	 *
	 * @return the updated by of this code detail
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this code detail.
	 *
	 * @param updatedBy the updated by of this code detail
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CodeDetail codeDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CodeDetail> toCacheModel();

	@Override
	public CodeDetail toEscapedModel();

	@Override
	public CodeDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}