/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ComponentControl service. Represents a row in the &quot;component_control&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.ComponentControlModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.ComponentControlImpl}.
 * </p>
 *
 * @author Dave Man
 * @see ComponentControl
 * @see hk.org.hkbh.cms.outpatient.model.impl.ComponentControlImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.ComponentControlModelImpl
 * @generated
 */
@ProviderType
public interface ComponentControlModel extends BaseModel<ComponentControl> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a component control model instance should use the {@link ComponentControl} interface instead.
	 */

	/**
	 * Returns the primary key of this component control.
	 *
	 * @return the primary key of this component control
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this component control.
	 *
	 * @param primaryKey the primary key of this component control
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this component control.
	 *
	 * @return the ID of this component control
	 */
	public long getId();

	/**
	 * Sets the ID of this component control.
	 *
	 * @param id the ID of this component control
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this component control.
	 *
	 * @return the user ID of this component control
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this component control.
	 *
	 * @param userId the user ID of this component control
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the user role ID of this component control.
	 *
	 * @return the user role ID of this component control
	 */
	public Long getUserRoleId();

	/**
	 * Sets the user role ID of this component control.
	 *
	 * @param userRoleId the user role ID of this component control
	 */
	public void setUserRoleId(Long userRoleId);

	/**
	 * Returns the component ID of this component control.
	 *
	 * @return the component ID of this component control
	 */
	public Long getComponentId();

	/**
	 * Sets the component ID of this component control.
	 *
	 * @param componentId the component ID of this component control
	 */
	public void setComponentId(Long componentId);

	/**
	 * Returns the create of this component control.
	 *
	 * @return the create of this component control
	 */
	public Boolean getCreate();

	/**
	 * Sets the create of this component control.
	 *
	 * @param create the create of this component control
	 */
	public void setCreate(Boolean create);

	/**
	 * Returns the read of this component control.
	 *
	 * @return the read of this component control
	 */
	public Boolean getRead();

	/**
	 * Sets the read of this component control.
	 *
	 * @param read the read of this component control
	 */
	public void setRead(Boolean read);

	/**
	 * Returns the update of this component control.
	 *
	 * @return the update of this component control
	 */
	public Boolean getUpdate();

	/**
	 * Sets the update of this component control.
	 *
	 * @param update the update of this component control
	 */
	public void setUpdate(Boolean update);

	/**
	 * Returns the delete of this component control.
	 *
	 * @return the delete of this component control
	 */
	public Boolean getDelete();

	/**
	 * Sets the delete of this component control.
	 *
	 * @param delete the delete of this component control
	 */
	public void setDelete(Boolean delete);

	/**
	 * Returns the deny of this component control.
	 *
	 * @return the deny of this component control
	 */
	public Boolean getDeny();

	/**
	 * Sets the deny of this component control.
	 *
	 * @param deny the deny of this component control
	 */
	public void setDeny(Boolean deny);

	/**
	 * Returns the visible of this component control.
	 *
	 * @return the visible of this component control
	 */
	public Boolean getVisible();

	/**
	 * Sets the visible of this component control.
	 *
	 * @param visible the visible of this component control
	 */
	public void setVisible(Boolean visible);

	/**
	 * Returns the enable of this component control.
	 *
	 * @return the enable of this component control
	 */
	public Boolean getEnable();

	/**
	 * Sets the enable of this component control.
	 *
	 * @param enable the enable of this component control
	 */
	public void setEnable(Boolean enable);

	/**
	 * Returns the control_desc of this component control.
	 *
	 * @return the control_desc of this component control
	 */
	@AutoEscape
	public String getControl_desc();

	/**
	 * Sets the control_desc of this component control.
	 *
	 * @param control_desc the control_desc of this component control
	 */
	public void setControl_desc(String control_desc);

	/**
	 * Returns the create date of this component control.
	 *
	 * @return the create date of this component control
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this component control.
	 *
	 * @param createDate the create date of this component control
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this component control.
	 *
	 * @return the update date of this component control
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this component control.
	 *
	 * @param updateDate the update date of this component control
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this component control.
	 *
	 * @return the created by of this component control
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this component control.
	 *
	 * @param createdBy the created by of this component control
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this component control.
	 *
	 * @return the updated by of this component control
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this component control.
	 *
	 * @param updatedBy the updated by of this component control
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ComponentControl componentControl);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ComponentControl> toCacheModel();

	@Override
	public ComponentControl toEscapedModel();

	@Override
	public ComponentControl toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}