/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ComponentControlDto service. Represents a row in the &quot;Op_ComponentControlDto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.ComponentControlDtoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.ComponentControlDtoImpl}.
 * </p>
 *
 * @author Dave Man
 * @see ComponentControlDto
 * @see hk.org.hkbh.cms.outpatient.model.impl.ComponentControlDtoImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.ComponentControlDtoModelImpl
 * @generated
 */
@ProviderType
public interface ComponentControlDtoModel extends BaseModel<ComponentControlDto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a component control dto model instance should use the {@link ComponentControlDto} interface instead.
	 */

	/**
	 * Returns the primary key of this component control dto.
	 *
	 * @return the primary key of this component control dto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this component control dto.
	 *
	 * @param primaryKey the primary key of this component control dto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this component control dto.
	 *
	 * @return the ID of this component control dto
	 */
	public long getId();

	/**
	 * Sets the ID of this component control dto.
	 *
	 * @param id the ID of this component control dto
	 */
	public void setId(long id);

	/**
	 * Returns the component code of this component control dto.
	 *
	 * @return the component code of this component control dto
	 */
	@AutoEscape
	public String getComponentCode();

	/**
	 * Sets the component code of this component control dto.
	 *
	 * @param componentCode the component code of this component control dto
	 */
	public void setComponentCode(String componentCode);

	/**
	 * Returns the component name of this component control dto.
	 *
	 * @return the component name of this component control dto
	 */
	@AutoEscape
	public String getComponentName();

	/**
	 * Sets the component name of this component control dto.
	 *
	 * @param componentName the component name of this component control dto
	 */
	public void setComponentName(String componentName);

	/**
	 * Returns the component type code ID of this component control dto.
	 *
	 * @return the component type code ID of this component control dto
	 */
	public Long getComponentTypeCodeId();

	/**
	 * Sets the component type code ID of this component control dto.
	 *
	 * @param componentTypeCodeId the component type code ID of this component control dto
	 */
	public void setComponentTypeCodeId(Long componentTypeCodeId);

	/**
	 * Returns the detail code of this component control dto.
	 *
	 * @return the detail code of this component control dto
	 */
	@AutoEscape
	public String getDetailCode();

	/**
	 * Sets the detail code of this component control dto.
	 *
	 * @param detailCode the detail code of this component control dto
	 */
	public void setDetailCode(String detailCode);

	/**
	 * Returns the detail code display text en of this component control dto.
	 *
	 * @return the detail code display text en of this component control dto
	 */
	@AutoEscape
	public String getDetailCodeDisplayTextEn();

	/**
	 * Sets the detail code display text en of this component control dto.
	 *
	 * @param detailCodeDisplayTextEn the detail code display text en of this component control dto
	 */
	public void setDetailCodeDisplayTextEn(String detailCodeDisplayTextEn);

	/**
	 * Returns the detail code display text chi of this component control dto.
	 *
	 * @return the detail code display text chi of this component control dto
	 */
	@AutoEscape
	public String getDetailCodeDisplayTextChi();

	/**
	 * Sets the detail code display text chi of this component control dto.
	 *
	 * @param detailCodeDisplayTextChi the detail code display text chi of this component control dto
	 */
	public void setDetailCodeDisplayTextChi(String detailCodeDisplayTextChi);

	/**
	 * Returns the component seq of this component control dto.
	 *
	 * @return the component seq of this component control dto
	 */
	public Integer getComponentSeq();

	/**
	 * Sets the component seq of this component control dto.
	 *
	 * @param componentSeq the component seq of this component control dto
	 */
	public void setComponentSeq(Integer componentSeq);

	/**
	 * Returns the is menu item of this component control dto.
	 *
	 * @return the is menu item of this component control dto
	 */
	public Boolean getIsMenuItem();

	/**
	 * Sets the is menu item of this component control dto.
	 *
	 * @param isMenuItem the is menu item of this component control dto
	 */
	public void setIsMenuItem(Boolean isMenuItem);

	/**
	 * Returns the component desc of this component control dto.
	 *
	 * @return the component desc of this component control dto
	 */
	@AutoEscape
	public String getComponentDesc();

	/**
	 * Sets the component desc of this component control dto.
	 *
	 * @param componentDesc the component desc of this component control dto
	 */
	public void setComponentDesc(String componentDesc);

	/**
	 * Returns the url of this component control dto.
	 *
	 * @return the url of this component control dto
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this component control dto.
	 *
	 * @param url the url of this component control dto
	 */
	public void setUrl(String url);

	/**
	 * Returns the component level of this component control dto.
	 *
	 * @return the component level of this component control dto
	 */
	public Integer getComponentLevel();

	/**
	 * Sets the component level of this component control dto.
	 *
	 * @param componentLevel the component level of this component control dto
	 */
	public void setComponentLevel(Integer componentLevel);

	/**
	 * Returns the up component ID of this component control dto.
	 *
	 * @return the up component ID of this component control dto
	 */
	public Long getUpComponentId();

	/**
	 * Sets the up component ID of this component control dto.
	 *
	 * @param upComponentId the up component ID of this component control dto
	 */
	public void setUpComponentId(Long upComponentId);

	/**
	 * Returns the component control ID of this component control dto.
	 *
	 * @return the component control ID of this component control dto
	 */
	public Long getComponentControlId();

	/**
	 * Sets the component control ID of this component control dto.
	 *
	 * @param componentControlId the component control ID of this component control dto
	 */
	public void setComponentControlId(Long componentControlId);

	/**
	 * Returns the user ID of this component control dto.
	 *
	 * @return the user ID of this component control dto
	 */
	public Long getUserId();

	/**
	 * Sets the user ID of this component control dto.
	 *
	 * @param userId the user ID of this component control dto
	 */
	public void setUserId(Long userId);

	/**
	 * Returns the user role ID of this component control dto.
	 *
	 * @return the user role ID of this component control dto
	 */
	public Long getUserRoleId();

	/**
	 * Sets the user role ID of this component control dto.
	 *
	 * @param userRoleId the user role ID of this component control dto
	 */
	public void setUserRoleId(Long userRoleId);

	/**
	 * Returns the component ID of this component control dto.
	 *
	 * @return the component ID of this component control dto
	 */
	public Long getComponentId();

	/**
	 * Sets the component ID of this component control dto.
	 *
	 * @param componentId the component ID of this component control dto
	 */
	public void setComponentId(Long componentId);

	/**
	 * Returns the create of this component control dto.
	 *
	 * @return the create of this component control dto
	 */
	public Boolean getCreate();

	/**
	 * Sets the create of this component control dto.
	 *
	 * @param create the create of this component control dto
	 */
	public void setCreate(Boolean create);

	/**
	 * Returns the read of this component control dto.
	 *
	 * @return the read of this component control dto
	 */
	public Boolean getRead();

	/**
	 * Sets the read of this component control dto.
	 *
	 * @param read the read of this component control dto
	 */
	public void setRead(Boolean read);

	/**
	 * Returns the update of this component control dto.
	 *
	 * @return the update of this component control dto
	 */
	public Boolean getUpdate();

	/**
	 * Sets the update of this component control dto.
	 *
	 * @param update the update of this component control dto
	 */
	public void setUpdate(Boolean update);

	/**
	 * Returns the delete of this component control dto.
	 *
	 * @return the delete of this component control dto
	 */
	public Boolean getDelete();

	/**
	 * Sets the delete of this component control dto.
	 *
	 * @param delete the delete of this component control dto
	 */
	public void setDelete(Boolean delete);

	/**
	 * Returns the deny of this component control dto.
	 *
	 * @return the deny of this component control dto
	 */
	public Boolean getDeny();

	/**
	 * Sets the deny of this component control dto.
	 *
	 * @param deny the deny of this component control dto
	 */
	public void setDeny(Boolean deny);

	/**
	 * Returns the visible of this component control dto.
	 *
	 * @return the visible of this component control dto
	 */
	public Boolean getVisible();

	/**
	 * Sets the visible of this component control dto.
	 *
	 * @param visible the visible of this component control dto
	 */
	public void setVisible(Boolean visible);

	/**
	 * Returns the enable of this component control dto.
	 *
	 * @return the enable of this component control dto
	 */
	public Boolean getEnable();

	/**
	 * Sets the enable of this component control dto.
	 *
	 * @param enable the enable of this component control dto
	 */
	public void setEnable(Boolean enable);

	/**
	 * Returns the control desc of this component control dto.
	 *
	 * @return the control desc of this component control dto
	 */
	@AutoEscape
	public String getControlDesc();

	/**
	 * Sets the control desc of this component control dto.
	 *
	 * @param controlDesc the control desc of this component control dto
	 */
	public void setControlDesc(String controlDesc);

	/**
	 * Returns the create date of this component control dto.
	 *
	 * @return the create date of this component control dto
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this component control dto.
	 *
	 * @param createDate the create date of this component control dto
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this component control dto.
	 *
	 * @return the update date of this component control dto
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this component control dto.
	 *
	 * @param updateDate the update date of this component control dto
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this component control dto.
	 *
	 * @return the created by of this component control dto
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this component control dto.
	 *
	 * @param createdBy the created by of this component control dto
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this component control dto.
	 *
	 * @return the updated by of this component control dto
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this component control dto.
	 *
	 * @param updatedBy the updated by of this component control dto
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ComponentControlDto componentControlDto);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ComponentControlDto> toCacheModel();

	@Override
	public ComponentControlDto toEscapedModel();

	@Override
	public ComponentControlDto toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}