/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ImagingResult service. Represents a row in the &quot;imaging_result&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link hk.org.hkbh.cms.outpatient.model.impl.ImagingResultModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link hk.org.hkbh.cms.outpatient.model.impl.ImagingResultImpl}.
 * </p>
 *
 * @author Dave Man
 * @see ImagingResult
 * @see hk.org.hkbh.cms.outpatient.model.impl.ImagingResultImpl
 * @see hk.org.hkbh.cms.outpatient.model.impl.ImagingResultModelImpl
 * @generated
 */
@ProviderType
public interface ImagingResultModel extends BaseModel<ImagingResult> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a imaging result model instance should use the {@link ImagingResult} interface instead.
	 */

	/**
	 * Returns the primary key of this imaging result.
	 *
	 * @return the primary key of this imaging result
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this imaging result.
	 *
	 * @param primaryKey the primary key of this imaging result
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this imaging result.
	 *
	 * @return the ID of this imaging result
	 */
	public long getId();

	/**
	 * Sets the ID of this imaging result.
	 *
	 * @param id the ID of this imaging result
	 */
	public void setId(long id);

	/**
	 * Returns the patient ID of this imaging result.
	 *
	 * @return the patient ID of this imaging result
	 */
	public Long getPatientId();

	/**
	 * Sets the patient ID of this imaging result.
	 *
	 * @param patientId the patient ID of this imaging result
	 */
	public void setPatientId(Long patientId);

	/**
	 * Returns the episode ID of this imaging result.
	 *
	 * @return the episode ID of this imaging result
	 */
	public Long getEpisodeId();

	/**
	 * Sets the episode ID of this imaging result.
	 *
	 * @param episodeId the episode ID of this imaging result
	 */
	public void setEpisodeId(Long episodeId);

	/**
	 * Returns the order ID of this imaging result.
	 *
	 * @return the order ID of this imaging result
	 */
	public Long getOrderId();

	/**
	 * Sets the order ID of this imaging result.
	 *
	 * @param orderId the order ID of this imaging result
	 */
	public void setOrderId(Long orderId);

	/**
	 * Returns the lab name of this imaging result.
	 *
	 * @return the lab name of this imaging result
	 */
	public Boolean getLabName();

	/**
	 * Sets the lab name of this imaging result.
	 *
	 * @param labName the lab name of this imaging result
	 */
	public void setLabName(Boolean labName);

	/**
	 * Returns the report name of this imaging result.
	 *
	 * @return the report name of this imaging result
	 */
	public Boolean getReportName();

	/**
	 * Sets the report name of this imaging result.
	 *
	 * @param reportName the report name of this imaging result
	 */
	public void setReportName(Boolean reportName);

	/**
	 * Returns the lab result type code ID of this imaging result.
	 *
	 * @return the lab result type code ID of this imaging result
	 */
	public Long getLabResultTypeCodeId();

	/**
	 * Sets the lab result type code ID of this imaging result.
	 *
	 * @param labResultTypeCodeId the lab result type code ID of this imaging result
	 */
	public void setLabResultTypeCodeId(Long labResultTypeCodeId);

	/**
	 * Returns the severity code ID of this imaging result.
	 *
	 * @return the severity code ID of this imaging result
	 */
	public Long getSeverityCodeId();

	/**
	 * Sets the severity code ID of this imaging result.
	 *
	 * @param severityCodeId the severity code ID of this imaging result
	 */
	public void setSeverityCodeId(Long severityCodeId);

	/**
	 * Returns the remarks of this imaging result.
	 *
	 * @return the remarks of this imaging result
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this imaging result.
	 *
	 * @param remarks the remarks of this imaging result
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the create date of this imaging result.
	 *
	 * @return the create date of this imaging result
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this imaging result.
	 *
	 * @param createDate the create date of this imaging result
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the update date of this imaging result.
	 *
	 * @return the update date of this imaging result
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this imaging result.
	 *
	 * @param updateDate the update date of this imaging result
	 */
	public void setUpdateDate(Date updateDate);

	/**
	 * Returns the created by of this imaging result.
	 *
	 * @return the created by of this imaging result
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this imaging result.
	 *
	 * @param createdBy the created by of this imaging result
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the updated by of this imaging result.
	 *
	 * @return the updated by of this imaging result
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this imaging result.
	 *
	 * @param updatedBy the updated by of this imaging result
	 */
	public void setUpdatedBy(String updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ImagingResult imagingResult);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ImagingResult> toCacheModel();

	@Override
	public ImagingResult toEscapedModel();

	@Override
	public ImagingResult toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}