/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hk.org.hkbh.cms.outpatient.model.impl;

import aQute.bnd.annotation.ProviderType;

import hk.org.hkbh.cms.outpatient.model.CodeDetail;
import hk.org.hkbh.cms.outpatient.service.CodeDetailLocalServiceUtil;

/**
 * The extended model base implementation for the CodeDetail service. Represents a row in the &quot;code_detail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CodeDetailImpl}.
 * </p>
 *
 * @author Dave Man
 * @see CodeDetailImpl
 * @see CodeDetail
 * @generated
 */
@ProviderType
public abstract class CodeDetailBaseImpl extends CodeDetailModelImpl
	implements CodeDetail {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a code detail model instance should use the {@link CodeDetail} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CodeDetailLocalServiceUtil.addCodeDetail(this);
		}
		else {
			CodeDetailLocalServiceUtil.updateCodeDetail(this);
		}
	}
}