create table Op_CodeDto (
	code_detail_id INTEGER not null primary key,
	master_code VARCHAR(75) null,
	code_display_text_en VARCHAR(75) null,
	code_display_text_chi VARCHAR(75) null,
	code_active BOOLEAN,
	subcode_enabled BOOLEAN,
	code_remarks VARCHAR(75) null,
	detail_code VARCHAR(75) null,
	seq INTEGER,
	code_detail_display_text_en VARCHAR(75) null,
	code_detail_display_text_chi VARCHAR(75) null,
	code_detail_active BOOLEAN,
	level INTEGER,
	up_level_id INTEGER,
	code_detail_remarks VARCHAR(75) null,
	create_date DATE null,
	update_date DATE null,
	created_by VARCHAR(75) null,
	updated_by VARCHAR(75) null
);

create table Op_ComponentControlDto (
	id INTEGER not null primary key,
	component_code VARCHAR(75) null,
	component_name VARCHAR(75) null,
	component_type_code_id INTEGER,
	detail_code INTEGER,
	detail_code_display_text_en VARCHAR(75) null,
	detail_code_display_text_chi VARCHAR(75) null,
	component_seq INTEGER,
	is_menu_item BOOLEAN,
	component_desc VARCHAR(75) null,
	url VARCHAR(75) null,
	component_level INTEGER,
	up_component_id INTEGER,
	component_control_id INTEGER,
	user_id INTEGER,
	user_role_id INTEGER,
	component_id INTEGER,
	create BOOLEAN,
	read BOOLEAN,
	update BOOLEAN,
	delete BOOLEAN,
	deny BOOLEAN,
	visible BOOLEAN,
	enable BOOLEAN,
	control_desc VARCHAR(75) null,
	create_date DATE null,
	update_date DATE null,
	created_by VARCHAR(75) null,
	updated_by VARCHAR(75) null
);